#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# -*- mode: shell -*-

# (c) Copyright 2014 WibiData, Inc.
#
# See the NOTICE file distributed with this work for additional
# information regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ------------------------------------------------------------------------------

# This script sets copies the update-etc-hosts script to /usr/local/bin/ and
# writes a sudoers rule giving users belonging to the 'bento' group permission
# to run the /usr/local/bin/update-etc-hosts script as root without providing a
# password.

# Usage:
#
#    $ sudo bento-setup-sudoers
#

# ------------------------------------------------------------------------------

set -o nounset   # Fail when referencing undefined variables
set -o errexit   # Script exits on the first error
set -o pipefail  # Pipeline status failure if any command fails
if [[ ! -z "${DEBUG:-}" ]]; then
  source=$(basename "${BASH_SOURCE}")
  PS4="# ${source}":'${LINENO}: '
  set -x
fi

# ------------------------------------------------------------------------------

# Canonicalize a path into an absolute, symlink free path.
#
# Portable implementation of the GNU coreutils "readlink -f path".
# The '-f' option of readlink does not exist on MacOS, for instance.
#
# Args:
#   param $1: path to canonicalize.
# Stdout:
#   Prints the canonicalized path on stdout.
function resolve_symlink() {
  local target_file=$1

  if [[ -z "${target_file}" ]]; then
    echo ""
    return 0
  fi

  cd "$(dirname "${target_file}")"
  target_file=$(basename "${target_file}")

  # Iterate down a (possible) chain of symlinks
  local count=0
  while [[ -L "${target_file}" ]]; do
    if [[ "${count}" -gt 1000 ]]; then
      # Just stop here, we've hit 1,000 recursive symlinks. (cycle?)
      break
    fi

    target_file=$(readlink "${target_file}")
    cd $(dirname "${target_file}")
    target_file=$(basename "${target_file}")
    count=$(( ${count} + 1 ))
  done

  # Compute the canonicalized name by finding the physical path
  # for the directory we're in and appending the target file.
  local phys_dir=$(pwd -P)
  echo "${phys_dir}/${target_file}"
}

# ------------------------------------------------------------------------------

install_path="/usr/local/bin/"
update_etc_hosts_name="update-etc-hosts"
bento_group="bento"
bento_sudoers_rule="%bento ALL = (ALL) NOPASSWD: ${install_path}/${update_etc_hosts_name}"

bento_env_path="${BASH_SOURCE:-$0}"
bento_env_path=$(resolve_symlink "${bento_env_path}")

bento_scripts_dir="$(dirname "${bento_env_path}")"
update_etc_hosts_path="${bento_scripts_dir}/${update_etc_hosts_name}"
bento_sudoers_rule_path="$(dirname "${bento_scripts_dir}")/rules/bento"

if [ ! -f ${update_etc_hosts_path} ]; then
  echo "Unable to find update-etc-hosts script at: ${update_etc_hosts_path}"
  exit 1;
fi

# Copy the update-etc-hosts script to /usr/local/bin/.
cp "${update_etc_hosts_path}" "${install_path}"

# Validate the bento sudoers rule.
temp=$(mktemp /tmp/bento.sudoers.tmp.XXXXXX)
bento_sudoers_rule
visudo -cf "${temp}"

# Copy the bento sudoers rule to /etc/sudoers.d/.

# Check to see if /etc/sudoers has a #includedir /etc/sudoers.d/ directive.
# Print warning if not.

# --- MAC-SPECIFIC SECTION NEEDED ---
# Create a bento group.

# Add the current user to the bento group.
# Warn the user that they need to get a new session to see group add effects.
